services:
  - type: web
    name: buildsphere
    runtime: node
    rootDir: BACKEND
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
    disk:
      name: buildsphere-data
      mountPath: /opt/render/project/src/DATABASE
      sizeGB: 1
